name: ocarina
description: Play local audio files on flutter
version: 0.0.1
homepage: https://github.com/erickzanardo/ocarina

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: xyz.erick.ocarina
        pluginClass: OcarinaPlugin
      ios:
        pluginClass: OcarinaPlugin
